config/routes.rb
FinalProject::Application.routes.draw do
  
  resources :emails
  resources :contacts
  resources :users
  resources :sessions, :only => [:new, :create, :destory]
  
  root :to => "sessions#new"
  match 'signup', :to => "users#new"
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match 'addcontact' , :to => 'pages#addcontact'
  match 'profile' , :to => 'pages#profile'
  match 'message', :to => 'pages#message'
  match 'search', :to => "pages#search"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :phone, :address, :city, :state,:password
  
  validates :password, :presence => true,
                       :length => { :within => 5..40 }
  validates :name, :presence => true, :length => {:within => 3..40}
  validates_format_of :email, :presence => true,
                      :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates :address, :presence => true, :length => {:within => 1..40}
  validates :city, :presence => true, :length => {:within => 1..40}
  validates :state, :presence => true, :length => {:within => 1..40}
  validates :phone, :presence => true, :length => {:within => 10..10}
                       
  def has_password?(submitted_password)
    password == (submitted_password)
  end
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
  @title = "Index"
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @title = "Show"
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @title = "Sign Up"
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @title = "Edit Contact"
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to profile_path, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'layouts/body' %>
<center>
	<h1>Editing user</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
</div>
</center>

app/views/users/index.html.erb
<center>
<%= render 'layouts/body' %>
	<h1>Your Contacts</h1>
	<table>
	  <tr>
	    <th>Name</th>
	    <th>Email</th>
	    <th>Phone</th>
	    <th>Address</th>
	    <th>City</th>
	    <th>State</th>
	    <th>Password</th>
	    <th>Owner</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	
	<% @users.each do |user| %>
	  <tr>
	    <td><%= user.name %></td>
	    <td><%= user.email %></td>
	    <td><%= user.phone %></td>
	    <td><%= user.address %></td>
	    <td><%= user.city %></td>
	    <td><%= user.state %></td>
	    <td><%= user.password %></td>
	    <td><%= link_to 'Show', user %></td>
	    <td><%= link_to 'Edit', edit_user_path(user) %></td>
	    <td><%= link_to 'Delete', user, confirm: 'Are you sure?', method: :delete %></td>
	  </tr>
	<% end %>
	</table>
	
	<br />
	
	<%= link_to 'New Contact', addcontact_path %>
</div>
</center>

app/views/users/new.html.erb
<center>

	<h1>Sign Up</h1>
	
	<%= render 'form' %>
	<%= link_to 'Back', root_path %>
</center>

app/views/users/show.html.erb
<center>
	<%= render 'layouts/body' %>
	<p id="notice"><%= notice %></p>
	
	<p>
	  <b>Name:</b>
	  <%= @user.name %>
	</p>
	
	<p>
	  <b>Email:</b>
	  <%= @user.email %>
	</p>
	
	<p>
	  <b>Phone:</b>
	  <%= @user.phone %>
	</p>
	
	<p>
	  <b>Address:</b>
	  <%= @user.address %>
	</p>
	
	<p>
	  <b>City:</b>
	  <%= @user.city %>
	</p>
	
	<p>
	  <b>State:</b>
	  <%= @user.state %>
	</p>
	
	<p>
	  <b>Password:</b>
	  <%= @user.password %>
	</p>
		
	
	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Back', users_path %>
</div>
</center>