config/routes.rb
FinalProject::Application.routes.draw do
  
  resources :emails
  resources :contacts
  resources :users
  resources :sessions, :only => [:new, :create, :destory]
  
  root :to => "sessions#new"
  match 'signup', :to => "users#new"
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match 'addcontact' , :to => 'pages#addcontact'
  match 'profile' , :to => 'pages#profile'
  match 'message', :to => 'pages#message'
  match 'search', :to => "pages#search"

end

app/views/pages/addcontact.html.erb
<%= render 'layouts/body' %>
<center>
<h1>Add a contact</h1>	
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
    <%= f.hidden_field :user_id, :value => cookies[:remember_token] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</center>

app/views/pages/message.html.erb
<%= render 'layouts/body' %>

<center>
<h1>Listing emails</h1>

<table>
  <tr>
    <th>To</th>
    <th>From</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @emails.each do |email| %>
  <tr>
    <td><%= email.to %></td>
    <td><%= email.from %></td>
    <td><%= email.content %></td>
    <td><%= link_to 'Show', email %></td>
    <td><%= link_to 'Delete', email, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Email', new_email_path %>
</div>
</center>

app/views/pages/profile.html.erb
<center>
<%= render 'layouts/body' %>
	<p id="notice"><%= notice %></p>
	<h1>Your Information</h1>
	<p>
	  <b>Name:</b>
	  <%= @user.name %>
	</p>
	
	<p>
	  <b>Email:</b>
	  <%= @user.email %>
	</p>
	
	<p>
	  <b>Phone:</b>
	  <%= @user.phone %>
	</p>
	
	<p>
	  <b>Address:</b>
	  <%= @user.address %>
	</p>
	
	<p>
	  <b>City:</b>
	  <%= @user.city %>
	</p>
	
	<p>
	  <b>State:</b>
	  <%= @user.state %>
	</p>
	
	<p>
	  <b>Password:</b>
	  <%= @user.password %>
	</p>
	
	
	<%= link_to 'Edit', edit_user_path(@user) %> 
</div>
</center>

app/views/pages/search.html.erb
<center>
<%= render 'layouts/body' %>
<h1>Listing your contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.phone %></td>
    <td><%= contact.address %></td>
    <td><%= contact.city %></td>
    <td><%= contact.state %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Delete', contact, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', addcontact_path %>

</div>
</center>