config/routes.rb
FinalProject::Application.routes.draw do
  
  resources :emails
  resources :contacts
  resources :users
  resources :sessions, :only => [:new, :create, :destory]
  
  root :to => "sessions#new"
  match 'signup', :to => "users#new"
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match 'addcontact' , :to => 'pages#addcontact'
  match 'profile' , :to => 'pages#profile'
  match 'message', :to => 'pages#message'
  match 'search', :to => "pages#search"

end

app/views/layouts/_body.html.erb
<div id = "header">
	<ul id="headtabs">
		<li><%= link_to "Logout", signout_path %></li>
		<li><%= link_to 'Add Contact', addcontact_path %></li>
		<li><%= link_to "My Profile", profile_path%></li>
		<li><%= link_to "Search", search_path %></li>
		<li><%= link_to "Messages", message_path %></li>
	</ul>
</div>
<div id="sidebar">
	<table id="table" cellpadding="0" cellspacing="0">
		<tr>
		  <td><%= link_to "*", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "A", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "B", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "C", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "D", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "E", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "F", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "G", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "H", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "I", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "J", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "K", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "L", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "M", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "N", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "O", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "P", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "Q", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "R", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "S", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "T", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "U", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "V", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "W", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "X", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "Y", search_path %></td>
		</tr>
		<tr>
		  <td><%= link_to "Z", search_path %></td>
		</tr>
	</table>
</div>

app/views/layouts/_header.html.erb
<head>
  <title><%= @title %></title>
  	<%= stylesheet_link_tag    "Layout" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
	<%= render 'layouts/header' %>
<body>
	<div id = "container">
			<%= yield %>
	</div>
</body>
</html>